baseURL: "https://adonze.github.io/" 
title: Alexandre Donzé
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: papers/
          weight: 1
        - name: Software
          url: data/
          weight: 2 

params:
    description: "I am a researcher made (sort of) entrepreneur at Decyphir SAS."
    author: Alexandre Donzé
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Alexandre Donzé, PhD
          subtitle: "I am a researcher made (sort of) entrepreneur at [Decyphir SAS](https://decyphir.com). I study the formal design of cyber-physical systems, and I am interested in the intersection of formal methods, machine learning, and control theory."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Alex Donzé
          buttons:
#            - name: Papers
#              url: papers/
#            - name: Courses
#              url: courses/
#            - name: Software
#              url: data/
#            - name: Tags
#              url: tags/
    socialIcons:
#        - name: CV
#          url: cv.pdf
        - name: Email
          url: mailto:alex@decyphir.com
#        - name: Location
#          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=RVZOGsIAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/adonze
        
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Alexandre Donzé"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
